name: Create and publish Container Images

on:
  workflow_dispatch:


jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runners-linux
    steps:
    - run: |
        docker build -t win .
        docker images
