name: Create and publish Container Images

on:
  workflow_dispatch:


jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - run: |
        docker build -t win .
        docker images
